Controllers/TiposInconsistenciasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SitiosWeb.Model;

namespace SitiosWeb.Controllers
{
    public class TiposInconsistenciasController : Controller
    {
        private readonly Tiusr22plProyectoContext _context;

        public TiposInconsistenciasController(Tiusr22plProyectoContext context)
        {
            _context = context;
        }

        // GET: TiposInconsistencias
        public async Task<IActionResult> Index()
        {
            return View(await _context.TiposInconsistencias.ToListAsync());
        }

        // GET: TiposInconsistencias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tiposInconsistencias = await _context.TiposInconsistencias
                .FirstOrDefaultAsync(m => m.IdTipoInconsistencia == id);
            if (tiposInconsistencias == null)
            {
                return NotFound();
            }

            return View(tiposInconsistencias);
        }

        // GET: TiposInconsistencias/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TiposInconsistencias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdTipoInconsistencia,Descripcion,Estado")] TiposInconsistencias tiposInconsistencias)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tiposInconsistencias);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tiposInconsistencias);
        }

        // GET: TiposInconsistencias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tiposInconsistencias = await _context.TiposInconsistencias.FindAsync(id);
            if (tiposInconsistencias == null)
            {
                return NotFound();
            }
            return View(tiposInconsistencias);
        }

        // POST: TiposInconsistencias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdTipoInconsistencia,Descripcion,Estado")] TiposInconsistencias tiposInconsistencias)
        {
            if (id != tiposInconsistencias.IdTipoInconsistencia)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tiposInconsistencias);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TiposInconsistenciasExists(tiposInconsistencias.IdTipoInconsistencia))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tiposInconsistencias);
        }

        // GET: TiposInconsistencias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tiposInconsistencias = await _context.TiposInconsistencias
                .FirstOrDefaultAsync(m => m.IdTipoInconsistencia == id);
            if (tiposInconsistencias == null)
            {
                return NotFound();
            }

            return View(tiposInconsistencias);
        }

        // POST: TiposInconsistencias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tiposInconsistencias = await _context.TiposInconsistencias.FindAsync(id);
            if (tiposInconsistencias != null)
            {
                _context.TiposInconsistencias.Remove(tiposInconsistencias);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TiposInconsistenciasExists(int id)
        {
            return _context.TiposInconsistencias.Any(e => e.IdTipoInconsistencia == id);
        }
    }
}

Views/TiposInconsistencias/Create.cshtml
@model SitiosWeb.Model.TiposInconsistencias

@{
    Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="~/css/menuCRUD.css" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Variables del Sistema</title>
</head>
<body>
    <div id="contenedor">
        <div class="vertical-menu">
            <a href="/Home/menuCRUD" class="active">Menu</a>
            <a href="/Home/IndexActividades">Actividades</a>
            <a href="/Home/IndexInconsistencias">Inconcistencias</a>
            <a href="/Home/IndexPermisos">Permisos</a>
            <a href="/Home/IndexRebajos">Rebajos</a>
            <a href="/Home/IndexUsuarios">Usuarios</a>
            <a href="/Home/IndexDepartamentos">Departamentos</a>
            <a href="/Home/IndexPuestos">Puestos</a>
        </div>

        <div id="contenido">

            <h4>Tipos de Inconsistencias</h4>
            <hr />
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Descripcion" class="control-label"></label>
                            <input asp-for="Descripcion" class="form-control" />
                            <span asp-validation-for="Descripcion" class="text-danger"></span>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                            </label>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

            <div>
                <a asp-action="Index"></a>
            </div>

            @section Scripts {
                @{
                    await Html.RenderPartialAsync("_ValidationScriptsPartial");
                }
            }
        </div>

    </div>

</body>
</html>

Views/TiposInconsistencias/Delete.cshtml
@model SitiosWeb.Model.TiposInconsistencias

@{
    Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="~/css/menuCRUD.css" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Variables del Sistema</title>
</head>
<body>
    <div id="contenedor">
        <div class="vertical-menu">

            <a asp-controller="Home" asp-action="IndexActividades">Actividades</a>
            <a asp-controller="Home" asp-action="IndexInconsistencias">Inconsistencias</a>
            <a asp-controller="Home" asp-action="IndexPermisos">Permisos</a>
            <a asp-controller="Home" asp-action="IndexRebajos">Rebajos</a>
            <a asp-controller="Home" asp-action="IndexUsuarios">Usuarios</a>
            <a asp-controller="Home" asp-action="IndexDepartamentos">Departamentos</a>
            <a asp-controller="Home" asp-action="IndexPuestos">Puestos</a>
            <a asp-action="IndexSupervisor" asp-controller="Home"> Volver al menu</a>

        </div>

        <div id="contenido">
            <h3>Seguro de borrar esta inconsistencia?</h3>
            <div>
                <h4>Tipos de Inconsistencias</h4>
                <hr />
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Descripcion)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Descripcion)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Estado)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Estado)
                    </dd>
                </dl>

                <form asp-action="Delete">
                    <input type="hidden" asp-for="IdTipoInconsistencia" />
                    <input type="submit" value="Delete" class="btn btn-danger" /> |
                    <a asp-action="Index"></a>
                </form>
            </div>
        </div>

        <div id="pie">
            <a href="../Menu/menuSupervisor.html"> Volver al menu</a>
        </div>
    </div>

</body>
</html>

Views/TiposInconsistencias/Details.cshtml
@model SitiosWeb.Model.TiposInconsistencias

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>TiposInconsistencias</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdTipoInconsistencia">Edit</a> |
    <a asp-action="Index"></a>
</div>
</body>
</html>

Views/TiposInconsistencias/Edit.cshtml
@model SitiosWeb.Model.TiposInconsistencias

@{
    Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="~/css/menuCRUD.css" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Variables del Sistema</title>
</head>
<body>
    <div id="contenedor">
        <div class="vertical-menu">

            <a asp-controller="Home" asp-action="IndexActividades">Actividades</a>
            <a asp-controller="Home" asp-action="IndexInconsistencias">Inconsistencias</a>
            <a asp-controller="Home" asp-action="IndexPermisos">Permisos</a>
            <a asp-controller="Home" asp-action="IndexRebajos">Rebajos</a>
            <a asp-controller="Home" asp-action="IndexUsuarios">Usuarios</a>
            <a asp-controller="Home" asp-action="IndexDepartamentos">Departamentos</a>
            <a asp-controller="Home" asp-action="IndexPuestos">Puestos</a>
            <a asp-action="IndexSupervisor" asp-controller="Home"> Volver al menu</a>

        </div>

        <div id="contenido">

            <h4>Tipos de Inconsistencias</h4>
            <hr />
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="IdTipoInconsistencia" />
                        <div class="form-group">
                            <label asp-for="Descripcion" class="control-label"></label>
                            <input asp-for="Descripcion" class="form-control" />
                            <span asp-validation-for="Descripcion" class="text-danger"></span>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                            </label>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

            <div>
                <a asp-action="Index"></a>
            </div>

            @section Scripts {
                @{
                    await Html.RenderPartialAsync("_ValidationScriptsPartial");
                }
            }
        </div>


    </div>

</body>
</html>

Views/TiposInconsistencias/Index.cshtml
@model IEnumerable<SitiosWeb.Model.TiposInconsistencias>

@{
    Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="~/css/menuCRUD.css" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Variables del Sistema</title>
</head>
<body>
    <div id="contenedor">
        <div class="vertical-menu">

            <a asp-controller="Home" asp-action="IndexActividades">Actividades</a>
            <a asp-controller="Home" asp-action="IndexInconsistencias">Inconsistencias</a>
            <a asp-controller="Home" asp-action="IndexPermisos">Permisos</a>
            <a asp-controller="Home" asp-action="IndexRebajos">Rebajos</a>
            <a asp-controller="Home" asp-action="IndexUsuarios">Usuarios</a>
            <a asp-controller="Home" asp-action="IndexDepartamentos">Departamentos</a>
            <a asp-controller="Home" asp-action="IndexPuestos">Puestos</a>
            <a asp-action="IndexSupervisor" asp-controller="Home"> Volver al menu</a>

        </div>

        <div id="contenido">
            <p>
                <a asp-controller="TiposInconsistencias" asp-action="Create">Crear nueva inconsistencias</a>
            </p>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Descripcion)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Estado)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Descripcion)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Estado)
                            </td>
                            <td>
                                <a asp-controller="TiposInconsistencias" asp-action="Edit" asp-route-id="@item.IdTipoInconsistencia">Editar</a>
                                <a asp-controller="TiposInconsistencias" asp-action="Delete" asp-route-id="@item.IdTipoInconsistencia">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>

</body>
</html>