Controllers/DepartamentosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SitiosWeb.Model;

namespace SitiosWeb.Controllers
{
    public class DepartamentosController : Controller
    {
        private readonly Tiusr22plProyectoContext _context;

        public DepartamentosController(Tiusr22plProyectoContext context)
        {
            _context = context;
        }

        // GET: Departamentos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Departamentos.ToListAsync());
        }

        // GET: Departamentos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departamentos = await _context.Departamentos
                .FirstOrDefaultAsync(m => m.IdDepartamento == id);
            if (departamentos == null)
            {
                return NotFound();
            }

            return View(departamentos);
        }

        // GET: Departamentos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Departamentos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdDepartamento,NomDepartamento,Estado")] Departamentos departamentos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(departamentos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(departamentos);
        }

        // GET: Departamentos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departamentos = await _context.Departamentos.FindAsync(id);
            if (departamentos == null)
            {
                return NotFound();
            }
            return View(departamentos);
        }

        // POST: Departamentos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdDepartamento,NomDepartamento,Estado")] Departamentos departamentos)
        {
            if (id != departamentos.IdDepartamento)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(departamentos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartamentosExists(departamentos.IdDepartamento))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(departamentos);
        }

        // GET: Departamentos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departamentos = await _context.Departamentos
                .FirstOrDefaultAsync(m => m.IdDepartamento == id);
            if (departamentos == null)
            {
                return NotFound();
            }

            return View(departamentos);
        }

        // POST: Departamentos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var departamentos = await _context.Departamentos.FindAsync(id);
            if (departamentos != null)
            {
                _context.Departamentos.Remove(departamentos);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartamentosExists(int id)
        {
            return _context.Departamentos.Any(e => e.IdDepartamento == id);
        }
    }
}

Views/Departamentos/Create.cshtml
@model SitiosWeb.Model.Departamentos

@{
    Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="~/css/menuCRUD.css" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Variables del Sistema</title>
</head>
<body>
    <div id="contenedor">
        <div class="vertical-menu">
            <div class="vertical-menu">

                <a asp-controller="Home" asp-action="IndexActividades">Actividades</a>
                <a asp-controller="Home" asp-action="IndexInconsistencias">Inconsistencias</a>
                <a asp-controller="Home" asp-action="IndexPermisos">Permisos</a>
                <a asp-controller="Home" asp-action="IndexRebajos">Rebajos</a>
                <a asp-controller="Home" asp-action="IndexUsuarios">Usuarios</a>
                <a asp-controller="Home" asp-action="IndexDepartamentos">Departamentos</a>
                <a asp-controller="Home" asp-action="IndexPuestos">Puestos</a>
                <a asp-action="IndexSupervisor" asp-controller="Home"> Volver al menu</a>

            </div>
        </div>

        <div id="contenido">

            <h4>Departamentos</h4>
            <hr />
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="NomDepartamento" class="control-label"></label>
                            <input asp-for="NomDepartamento" class="form-control" />
                            <span asp-validation-for="NomDepartamento" class="text-danger"></span>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                            </label>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

            <div>
                <a asp-action="Index"></a>
            </div>

            @section Scripts {
                @{
                    await Html.RenderPartialAsync("_ValidationScriptsPartial");
                }
            }
        </div>


    </div>

</body>
</html>

Views/Departamentos/Delete.cshtml
@model SitiosWeb.Model.Departamentos

@{
    Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="~/css/menuCRUD.css" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Variables del Sistema</title>
</head>
<body>
    <div id="contenedor">
        <div class="vertical-menu">
            <div class="vertical-menu">

                <a asp-controller="Home" asp-action="IndexActividades">Actividades</a>
                <a asp-controller="Home" asp-action="IndexInconsistencias">Inconsistencias</a>
                <a asp-controller="Home" asp-action="IndexPermisos">Permisos</a>
                <a asp-controller="Home" asp-action="IndexRebajos">Rebajos</a>
                <a asp-controller="Home" asp-action="IndexUsuarios">Usuarios</a>
                <a asp-controller="Home" asp-action="IndexDepartamentos">Departamentos</a>
                <a asp-controller="Home" asp-action="IndexPuestos">Puestos</a>
                <a asp-action="IndexSupervisor" asp-controller="Home"> Volver al menu</a>

            </div>
        </div>

        <div id="contenido">

            <h3>Seguro de Borrar el departamento?</h3>
            <div>
                <h4>Departamentos</h4>
                <hr />
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.NomDepartamento)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.NomDepartamento)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Estado)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Estado)
                    </dd>
                </dl>

                <form asp-action="Delete">
                    <input type="hidden" asp-for="IdDepartamento" />
                    <input type="submit" value="Delete" class="btn btn-danger" /> |
                    <a asp-action="Index"></a>
                </form>
            </div>
        </div>

    </div>

</body>
</html>

Views/Departamentos/Details.cshtml
@model SitiosWeb.Model.Departamentos

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>Departamentos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomDepartamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomDepartamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdDepartamento">Edit</a> |
    <a asp-action="Index"></a>
</div>
</body>
</html>

Views/Departamentos/Edit.cshtml
@model SitiosWeb.Model.Departamentos

@{
    Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="~/css/menuCRUD.css" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Variables del Sistema</title>
</head>
<body>
    <div id="contenedor">
        <div class="vertical-menu">
            <div class="vertical-menu">

                <a asp-controller="Home" asp-action="IndexActividades">Actividades</a>
                <a asp-controller="Home" asp-action="IndexInconsistencias">Inconsistencias</a>
                <a asp-controller="Home" asp-action="IndexPermisos">Permisos</a>
                <a asp-controller="Home" asp-action="IndexRebajos">Rebajos</a>
                <a asp-controller="Home" asp-action="IndexUsuarios">Usuarios</a>
                <a asp-controller="Home" asp-action="IndexDepartamentos">Departamentos</a>
                <a asp-controller="Home" asp-action="IndexPuestos">Puestos</a>
                <a asp-action="IndexSupervisor" asp-controller="Home"> Volver al menu</a>

            </div>
        </div>

        <div id="contenido">

            <h4>Departamentos</h4>
            <hr />
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="IdDepartamento" />
                        <div class="form-group">
                            <label asp-for="NomDepartamento" class="control-label"></label>
                            <input asp-for="NomDepartamento" class="form-control" />
                            <span asp-validation-for="NomDepartamento" class="text-danger"></span>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                            </label>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

            <div>
                <a asp-action="Index"></a>
            </div>

            @section Scripts {
                @{
                    await Html.RenderPartialAsync("_ValidationScriptsPartial");
                }
            }
        </div>

    </div>

</body>
</html>

Views/Departamentos/Index.cshtml
@model IEnumerable<SitiosWeb.Model.Departamentos>

@{
    Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="~/css/menuCRUD.css" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Variables del Sistema</title>
</head>
<body>
    <div id="contenedor">
        <div class="vertical-menu">

            <a asp-controller="Home" asp-action="IndexActividades">Actividades</a>
            <a asp-controller="Home" asp-action="IndexInconsistencias">Inconsistencias</a>
            <a asp-controller="Home" asp-action="IndexPermisos">Permisos</a>
            <a asp-controller="Home" asp-action="IndexRebajos">Rebajos</a>
            <a asp-controller="Home" asp-action="IndexUsuarios">Usuarios</a>
            <a asp-controller="Home" asp-action="IndexDepartamentos">Departamentos</a>
            <a asp-controller="Home" asp-action="IndexPuestos">Puestos</a>
            <a asp-action="IndexSupervisor" asp-controller="Home"> Volver al menu</a>

        </div>

        <div id="contenido">

            <p>
                <a asp-controller="DepartamentosController" asp-action="Create">Crear Nuevo</a>
            </p>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.NomDepartamento)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Estado)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.NomDepartamento)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Estado)
                            </td>
                            <td>
                                <a asp-controller="Departamentos" asp-action="Edit" asp-route-id="@item.IdDepartamento">Editar</a>
                                <a asp-controller="Departamentos" asp-action="Delete" asp-route-id="@item.IdDepartamento">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>

</body>
</html>