Controllers/ConfiguracionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SitiosWeb.Model;

namespace SitiosWeb.Controllers
{
    public class ConfiguracionesController : Controller
    {
        private readonly Tiusr22plProyectoContext _context;

        public ConfiguracionesController(Tiusr22plProyectoContext context)
        {
            _context = context;
        }

        // GET: Configuraciones
        public async Task<IActionResult> Index()
        {
            return View(await _context.Configuraciones.ToListAsync());
        }

        // GET: Configuraciones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var configuraciones = await _context.Configuraciones
                .FirstOrDefaultAsync(m => m.IdConfiguraciones == id);
            if (configuraciones == null)
            {
                return NotFound();
            }

            return View(configuraciones);
        }

        // GET: Configuraciones/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Configuraciones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdConfiguraciones,NomConfiguracion,ValorConfig,NumConfig")] Configuraciones configuraciones)
        {
            if (ModelState.IsValid)
            {
                _context.Add(configuraciones);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(configuraciones);
        }

        // GET: Configuraciones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var configuraciones = await _context.Configuraciones.FindAsync(id);
            if (configuraciones == null)
            {
                return NotFound();
            }
            return View(configuraciones);
        }

        // POST: Configuraciones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdConfiguraciones,NomConfiguracion,ValorConfig,NumConfig")] Configuraciones configuraciones)
        {
            if (id != configuraciones.IdConfiguraciones)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(configuraciones);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConfiguracionesExists(configuraciones.IdConfiguraciones))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(configuraciones);
        }

        // GET: Configuraciones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var configuraciones = await _context.Configuraciones
                .FirstOrDefaultAsync(m => m.IdConfiguraciones == id);
            if (configuraciones == null)
            {
                return NotFound();
            }

            return View(configuraciones);
        }

        // POST: Configuraciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var configuraciones = await _context.Configuraciones.FindAsync(id);
            if (configuraciones != null)
            {
                _context.Configuraciones.Remove(configuraciones);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ConfiguracionesExists(int id)
        {
            return _context.Configuraciones.Any(e => e.IdConfiguraciones == id);
        }
        public async Task<IActionResult> BloquearDias()
        {
            return View(await _context.BloqueoDias.ToListAsync());
        }
        public async Task<IActionResult> ManejarDias(int id, string descripcion, string tipo, string dia)
        {
            BloqueoDias ids = null;
            if (id != null)
            {
                ids = _context.BloqueoDias.FirstOrDefault(c => c.DayId == id);
            }

            switch (tipo)
            {
                case "0":
                    _context.BloqueoDias.Add(new BloqueoDias
                    {
                        Descripcion = descripcion,
                        Tipo = 0,
                        Day = DateOnly.Parse(dia)
                    });
                    TempData["Success"] = "Dia bloqueado por la empresa correctamente.";

                    break;
                case "1":
                    _context.BloqueoDias.Add(new BloqueoDias
                    {
                        Descripcion = descripcion,
                        Tipo = 1,
                        Day = DateOnly.Parse(dia)
                    });
                    TempData["Success"] = "Dia festivo agregado correctamente.";


                    break;

                case "2":
                    if (ids != null)
                    {
                        ids.Descripcion = descripcion;
                        _context.BloqueoDias.Update(ids);
                    }
                    TempData["Success"] = "Dia actualizado correctamente.";
                    break;

                case "3":
                    if (ids != null)
                    {
                        _context.BloqueoDias.Remove(ids);
                    }
                    TempData["Success"] = "Dia eliminado correctamente.";

                    break;

                default:
                    break;
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("BloquearDias");
        }

    }
}

Views/Configuraciones/BloquearDias.cshtml
@model IEnumerable<SitiosWeb.Model.BloqueoDias>;
@{
    bool edita;
    if (User.IsInRole("JEFATURA"))
    {
        Layout = "~/Views/Shared/_LayoutJefatura.cshtml";
        edita = false ;
    }
    else if (User.IsInRole("SUPERVISOR"))
    {
        Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
        edita = true;
    }
    else if (User.IsInRole("COLABORADOR"))
    {
        Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
        edita = false;
    }
    else
    {
        edita = false;
    }
}
}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="~/css/styles.css" />
    <link rel="stylesheet" type="text/css" href="~/css/calendarBlock.css" />
    <script src="~/js/blockDias.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
</head>

<body>
    <div class="contains">
        <div class="head">
            <img src="https://ld-wp73.template-help.com/imperion/corporatelanding/wp-content/uploads/2019/07/img-1-sec.png" alt="Form Image" class="image">
            <div class="titles">
                <h1 class="title-page">Bloqueo de </h1>
                <h1 class="title-span">Dias</h1>

            </div>
        </div>
        <label class="error" style="display: none;"></label>
        <label class="success" style="display: none;"></label>



        <div class="calendar" ID="calendar">
            <div class="calendar-header">
                <button id="prevMonth">< </button>
                <h2 id="monthYear"></h2>
                <button id="nextMonth"> ></button>
            </div>
            <div class="days" id="calendarDays">
            </div>

        </div>
        <div id="dayBlock" class="modal">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 id="tipos">Bloqueo de días</h2>
                    <span id="close" class="close">&times;</span>
                </div>

                <form id="modalForm" asp-action="ManejarDias">

                    <div class="select-container">
                        <label style="font-size:20px;  margin-bottom:10px;">Descripción</label><br />
                        <textarea name="descripcion" id="descripcion" required maxlength="300"
                                  style="height: 100px; width: 400px; resize: none; margin-bottom: 10px; line-height: 70px; overflow: hidden;"></textarea>
                        <input type="text" name="id" id="idDia" hidden />
                        <input type="text" name="tipo" id="tipo" hidden />
                        <input type="text" name="dia" id="dia" hidden />

                    </div>
                    <div class="buttons" style="gap:5rem; margin:0 auto;">
                        <button type="submit" style="display:none;" id="bloquear">Bloquear días </button>
                        <button type="submit" style="display:none;" id="festivo">Añadir festivo</button>
                        <button type="submit" style="display:none;" id="editar">Editar</button>
                        <button type="submit" style="display:none;" id="eliminar">Eliminar</button>
                    </div>

                </form>
            </div>

        </div>
    </div>
</body>
<script>
    let diaMarcar = [
    @for (var i = 0; i < Model.Count(); i++)
    {
        @: '@Model.ElementAt(i).Day'
        @if (i < Model.Count() - 1)
        {
            @:,

        }
    }
];
    let tipoDia = [
    @for (var i = 0; i < Model.Count(); i++)
    {
        @: '@Model.ElementAt(i).Tipo'
        @if (i < Model.Count() - 1)
        {
            @:,
        }
    }
];
    let idsDia = [
    @for (var i = 0; i < Model.Count(); i++)
    {
        @: '@Model.ElementAt(i).DayId'
        @if (i < Model.Count() - 1)
        {
            @:,
        }
    }
];
    let DiaDescripcion = [
    @for (var i = 0; i < Model.Count(); i++)
    {
        @: '@Model.ElementAt(i).Descripcion'
        @if (i < Model.Count() - 1)
        {
            @:,
        }
    }
];

</script>
<script>
    let edita = @edita.ToString().ToLower();
    document.addEventListener('DOMContentLoaded', function () {

        const successLabel = document.querySelector('.success');
        const successMessage = '@TempData["Success"]'.trim();

        if (successMessage === '') {
            successLabel.style.display = 'none';
            successLabel.classList.remove('fadeIn', 'fadeOut');
        } else {
            successLabel.textContent = successMessage;
            successLabel.style.display = 'block';
            successLabel.classList.remove('fadeOut');
            successLabel.classList.add('fadeIn');

            setTimeout(() => {
                successLabel.classList.remove('fadeIn');
                successLabel.classList.add('fadeOut');
                setTimeout(() => {
                    successLabel.style.display = 'none';
                    successLabel.classList.remove('fadeOut');
                }, 2000);
            }, 2000);
        }
    });
</script>

Views/Configuraciones/Create.cshtml
@model SitiosWeb.Model.Configuraciones

@{
    Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="~/css/configuraciones.css" />
    <meta name="viewport" content="width=device-width" />
    <title>Crear Nueva Configuracion</title>
</head>
<body>

<hr />
<div class="row">
    <p>
            <h4>Configuraciones</h4>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                    <label for="campoTexto1" class="control-label">Nombre de la configuracion:</label>
                    <input type="text" id="campoTexto1" name="NomConfiguracion" class="form-control" />
            </div>
            <div class="form-group">
                    <label for="campoTexto1" class="control-label">Valor de la configuracion:</label>
                    <input type="text" id="campoTexto1" name="ValorConfig" class="form-control" />
            </div>
            <div class="form-group">
                    <label for="campoTexto1" class="control-label">Numero de la configuracion:</label>
                    <input type="text" id="campoTexto1" name="NumConfig" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </p>
</div>

<div>
    <a class="btn-warning" asp-action="Index"></a>
</div>

</body>
</html>

Views/Configuraciones/Delete.cshtml
@model SitiosWeb.Model.Configuraciones

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Configuraciones</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomConfiguracion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomConfiguracion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorConfig)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorConfig)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumConfig)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumConfig)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdConfiguraciones" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index"></a>
    </form>
</div>
</body>
</html>

Views/Configuraciones/Edit.cshtml
@model SitiosWeb.Model.Configuraciones

@{
    Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="~/css/configuraciones.css" />
    <title>Edit</title>
</head>
<body>

<hr />
<div class="row">
    <p>
            <h4>Configuraciones</h4>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdConfiguraciones" />
            <div class="form-group">
                <label asp-for="NomConfiguracion" class="control-label"></label>
                <input asp-for="NomConfiguracion" class="form-control" />
                <span asp-validation-for="NomConfiguracion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorConfig" class="control-label"></label>
                <input asp-for="ValorConfig" class="form-control" />
                <span asp-validation-for="ValorConfig" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumConfig" class="control-label"></label>
                <input asp-for="NumConfig" class="form-control" />
                <span asp-validation-for="NumConfig" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </p>
</div>

<div>
    <a asp-action="Index"></a>
</div>

</body>
</html>

Views/Configuraciones/Index.cshtml
@model IEnumerable<SitiosWeb.Model.Configuraciones>

@{
    Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="~/css/configuraciones.css" />
    <script src="https://kit.fontawesome.com/4d99acc268.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width" />
    <title>Configuraciones</title>
</head>
<body>
<p>
    <a asp-controller="Configuraciones" class="btn-success" asp-action="Create">Agregar Nueva</a>
        <a class="btn-primary" asp-controller="Configuraciones" asp-action="BloquearDias">Bloquear Dias</a>


    </p>
<div id="contenido">

        @foreach (var item in Model)
        {
            <p>
                <i class="fa-solid fa-gear"></i>
                <br />
                ID de la Configuracion: @item.IdConfiguraciones.ToString()
                <br />
                <br />
                Nombre de Configuracion: @item.NomConfiguracion.ToString()
                <br />
                <br />
                Valor de la Configuracion: @item.ValorConfig.ToString()
                <br />
                <br />
                Numero de la Configuracion: @item.NumConfig.ToString()
                <br />
                <br />
                <a asp-controller="Configuraciones" asp-action="Edit" class="btn-warning" asp-route-id="@item.IdConfiguraciones">Editar</a> |
                <a asp-controller="Configuraciones" asp-action="Delete" class="btn-danger" asp-route-id="@item.IdConfiguraciones">Borrar</a>
            </p>
        }
</div>

</body>
</html>