Controllers/RebajosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SitiosWeb.Model;

namespace SitiosWeb.Controllers
{
    public class RebajosController : Controller
    {
        private readonly Tiusr22plProyectoContext _context;

        public RebajosController(Tiusr22plProyectoContext context)
        {
            _context = context;
        }

        // GET: Rebajos
        public async Task<IActionResult> Index()
        {
            var tiusr22plProyectoContext = _context.Rebajos.Include(r => r.IdColaboradorNavigation).Include(r => r.IdTipoRebajoNavigation).Include(r => r.IdValidadorNavigation).Include(r => r.InconsistenciaNavigation);
            return View(await tiusr22plProyectoContext.ToListAsync());
        }

        public async Task<IActionResult> GetTiposInconsistencias()
        {
            var tiposInconsistencias = await _context.TiposInconsistencias
                .Select(ti => new
                {
                    IdTipoInconsistencia = ti.IdTipoInconsistencia,
                    Descripcion = ti.Descripcion
                })
                .ToListAsync();

            return Json(tiposInconsistencias);
        }

        // GET: Rebajos/Create
        public IActionResult Create()
        {
            ViewData["IdColaborador"] = new SelectList(_context.Colaboradores, "Identificacion", "Identificacion");
            ViewData["IdTipoRebajo"] = new SelectList(_context.TiposRebajos, "IdTipoRebajo", "IdTipoRebajo");
            ViewData["IdValidador"] = new SelectList(_context.Colaboradores, "Identificacion", "Identificacion");
            ViewData["Inconsistencia"] = new SelectList(_context.Inconsistencias, "IdInconsistencia", "IdInconsistencia");
            return View();
        }

        public async Task<IActionResult> aplicarRebajo(string colab, DateOnly fecha, int idtipoinconsistencia, int IdTipoRebajo) 
        {

            var colaborador = _context.Colaboradores
                .FirstOrDefault(c => c.Identificacion == colab);

            var rebajo = new Rebajos
            {
                IdColaborador = colab,
                IdValidador = Request.Cookies["Id"],
                FechaRebajo = fecha,
                Inconsistencia = idtipoinconsistencia,
                IdTipoRebajo = IdTipoRebajo,
                Aprobacion = true
            };

            _context.Rebajos.Add(rebajo);
            await _context.SaveChangesAsync();

            string nombre = colaborador.Nombre;
            string correo = colaborador.Correo;

            EnviarCorreo(correo, "Rebajo aplicado", $"Estimado {nombre} se le ha aplicado un rebajo, por informacion consulte a su jefatura");

            return View("~/Views/Rebajos/Index.cshtml");

        }

        private void EnviarCorreo(string destinatario, string asunto, string cuerpo)
        {
            try
            {
                SmtpClient smtpClient = new SmtpClient("smtp.gmail.com")
                {
                    Port = 587,
                    Credentials = new NetworkCredential("calderonmora6@gmail.com", "qsre xvxi yyvt flyw"),
                    EnableSsl = true,
                };

                MailMessage mailMessage = new MailMessage
                {
                    From = new MailAddress("calderonmora6@gmail.com"),
                    Subject = asunto,
                    Body = cuerpo,
                    IsBodyHtml = false,
                };

                mailMessage.To.Add(destinatario);

                smtpClient.Send(mailMessage);
                Console.WriteLine("Correo enviado con éxito.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al enviar el correo: {ex.Message}");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdRebajo,IdColaborador,IdValidador,FechaRebajo,Inconsistencia,IdTipoRebajo,Aprobacion")] Rebajos rebajos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rebajos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdColaborador"] = new SelectList(_context.Colaboradores, "Identificacion", "Identificacion", rebajos.IdColaborador);
            ViewData["IdTipoRebajo"] = new SelectList(_context.TiposRebajos, "IdTipoRebajo", "IdTipoRebajo", rebajos.IdTipoRebajo);
            ViewData["IdValidador"] = new SelectList(_context.Colaboradores, "Identificacion", "Identificacion", rebajos.IdValidador);
            ViewData["Inconsistencia"] = new SelectList(_context.Inconsistencias, "IdInconsistencia", "IdInconsistencia", rebajos.Inconsistencia);
            return View(rebajos);
        }

        // GET: Rebajos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rebajos = await _context.Rebajos.FindAsync(id);
            if (rebajos == null)
            {
                return NotFound();
            }
            ViewData["IdColaborador"] = new SelectList(_context.Colaboradores, "Identificacion", "Identificacion", rebajos.IdColaborador);
            ViewData["IdTipoRebajo"] = new SelectList(_context.TiposRebajos, "IdTipoRebajo", "IdTipoRebajo", rebajos.IdTipoRebajo);
            ViewData["IdValidador"] = new SelectList(_context.Colaboradores, "Identificacion", "Identificacion", rebajos.IdValidador);
            ViewData["Inconsistencia"] = new SelectList(_context.Inconsistencias, "IdInconsistencia", "IdInconsistencia", rebajos.Inconsistencia);
            return View(rebajos);
        }

        // POST: Rebajos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdRebajo,IdColaborador,IdValidador,FechaRebajo,Inconsistencia,IdTipoRebajo,Aprobacion")] Rebajos rebajos)
        {
            if (id != rebajos.IdRebajo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rebajos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RebajosExists(rebajos.IdRebajo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdColaborador"] = new SelectList(_context.Colaboradores, "Identificacion", "Identificacion", rebajos.IdColaborador);
            ViewData["IdTipoRebajo"] = new SelectList(_context.TiposRebajos, "IdTipoRebajo", "IdTipoRebajo", rebajos.IdTipoRebajo);
            ViewData["IdValidador"] = new SelectList(_context.Colaboradores, "Identificacion", "Identificacion", rebajos.IdValidador);
            ViewData["Inconsistencia"] = new SelectList(_context.Inconsistencias, "IdInconsistencia", "IdInconsistencia", rebajos.Inconsistencia);
            return View(rebajos);
        }

        public IActionResult HistoricoRebajos()
        {
            dynamic result=0;
            if (User.IsInRole("COLABORADOR")) 
            {
                result = _context.Rebajos.Where(r => r.IdColaborador == Request.Cookies["Id"])
                    .Include(r => r.IdTipoRebajoNavigation)
                    .ToList();
            }
            else if (User.IsInRole("JEFATURA")) 
            { 
                ViewBag.Nombres = _context.Colaboradores.ToList();
                result = _context.Rebajos.Where(r => r.IdColaboradorNavigation.IdPuestoNavigation.IdDepartamentoNavigation.IdDepartamento == int.Parse(Request.Cookies["IDDepartamento"]))
                                        .Include(r => r.IdTipoRebajoNavigation)

                    .ToList();
            }
            else if (User.IsInRole("SUPERVISOR"))
            {
                ViewBag.Nombres = _context.Colaboradores.ToList();
                result = _context.Rebajos
                    .Include(r => r.IdTipoRebajoNavigation)
                    .ToList();
               
            }
            
            return View(result);
        }
        private bool RebajosExists(int id)
        {
            return _context.Rebajos.Any(e => e.IdRebajo == id);
        }

    }
}

Views/Rebajos/HistoricoRebajos.cshtml
@model IEnumerable<SitiosWeb.Model.Rebajos>;
@using System.Globalization
@{
    if (User.IsInRole("JEFATURA"))
    {
        Layout = "~/Views/Shared/_LayoutJefatura.cshtml";
    }
    else if (User.IsInRole("SUPERVISOR"))
    {
        Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
    }
    else if (User.IsInRole("COLABORADOR"))
    {
        Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
    }
    var cultura = new CultureInfo("es-ES");
    var Nombres = ViewBag.Nombres as IEnumerable<SitiosWeb.Model.Colaboradores>;
}
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Selección de Vacaciones Colectivas</title>
    <link rel="stylesheet" type="text/css" href="~/css/styles.css" />
    <link rel="stylesheet" type="text/css" href="~/css/table.css" />
</head>

<body>

    <div class="content-table">

        <div class="contenedor">
            <h2 id="titulolbl">Historicos de rebajos</h2>


            <label class="success" id="succ"></label>
            @if (Model.Count() == 0)
            {
                <label style="font-weight:bold; font-size:30px; align-self:center;">No hay históricos</label>
            }
            else if (Model.Count() >= 9)
            {
                <div class="TablaForm-Container">

                    <table class="table table-striped tabla">
                        <thead>
                            <tr>
                                <th>
                                    <label>Nombre Colaborador</label>
                                </th>
                                <th>
                                    <label>Nombre Validador</label>
                                </th>
                                <th>
                                    <label>Fecha del rebajo</label>
                                </th>
                                <th>
                                    <label>Tipo de rebajo</label>
                                </th>
                                <th>
                                    <label>Aprobacion</label>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                var nombreColab = Nombres.FirstOrDefault(c => c.Identificacion == item.IdColaborador);
                                var nombreValid = Nombres.FirstOrDefault(c => c.Identificacion == item.IdValidador);


                                <tr>
                                    <td>

                                        @Html.DisplayFor(modelItem => nombreColab != null ? nombreColab.Nombre + " " + nombreColab.Apellidos : "Nombre no encontrado")
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => nombreValid != null ? nombreValid.Nombre + " " + nombreValid.Apellidos : "Nombre no encontrado")

                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FechaRebajo)

                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.IdTipoRebajoNavigation.Descripcion)

                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Aprobacion)

                                    </td>

                                </tr>

                            }
                        </tbody>
                    </table>
                </div>

            }
            else
            {
                <div class="tarjetas">
                    @foreach (var item in Model)
                    {
                        var nombreValid = Nombres.FirstOrDefault(c => c.Identificacion == item.IdValidador);

                        @if (User.IsInRole("JEFATURA") || User.IsInRole("SUPERVISOR"))
                        {
                            var nombreColab = Nombres.FirstOrDefault(c => c.Identificacion == item.IdColaborador);

                            <div href="#" class="tarjeta">
                                <p>Nombre Colaborador:</p>   @nombreColab.Nombre @nombreColab.Apellidos
                                <p>Nombre Validador:</p> @nombreValid.Nombre @nombreValid.Apellidos
                                <p>Fecha del rebajo:</p> @item.FechaRebajo.ToString("d 'de' MMMM", cultura)
                                <p>Tipo de rebajo:</p> @item.IdTipoRebajoNavigation.Descripcion
                                <p>Aprobacion:</p> @item.Aprobacion
                            </div>
                        }
                        else
                        {
                            <div href="#" class="tarjeta">
                                <p>Nombre Colaborador:</p>   @Context.Request.Cookies["Nombre"]
                                <p>Nombre Validador:</p> @nombreValid.Nombre @nombreValid.Apellidos
                                <p>Fecha del rebajo:</p> @item.FechaRebajo.ToString("d 'de' MMMM", cultura)
                                <p>Tipo de rebajo:</p> @item.IdTipoRebajoNavigation.Descripcion
                                <p>Aprobacion:</p> @item.Aprobacion
                            </div>
                        }

                    }
                </div>

            }
            <img src="https://ld-wp73.template-help.com/imperion/corporatelanding/wp-content/uploads/2019/07/img-subscribe-737x1024.png" alt="Form Image">
            
        </div>
    </div>
</body>
</html>

Views/Rebajos/Index.cshtml
@model IEnumerable<SitiosWeb.Model.Rebajos>

@{
    Layout = "~/Views/Shared/_LayoutSupervisor.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="~/css/justificaciones.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Aplicar Rebajo</title>
</head>
<body>
 <div class="container">
        <h2>Aplicar Rebajo</h2>
        <hr />
        <div class="row">
            <div class="col-md-6">
                <form asp-controller="Rebajos" asp-action="aplicarRebajo">

                    <div class="form-group">
                        <label for="idInconsistencia" class="control-label">Colaborador: </label>
                        <input type="text" id="" name="colab" class="form-control" value=""  />
                    </div>

                    <div class="form-group">
                        <label for="fecha" class="control-label">Fecha:</label>
                        <input type="date" id="fecha" name="fecha" class="form-control" />
                    </div>

                    <div class="form-group">
                        <label for="comboBox3" class="control-label">Tipo Inconsistencia:</label>
                        <select id="comboBox3" name="idtipoinconsistencia" class="form-control">
                            <option value="">Cargando...</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="comboBox4" class="control-label">Tipo Rebajo:</label>
                        <select id="comboBox4" name="IdTipoRebajo" class="form-control">
                            <option value="">Cargando...</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Enviar" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
 </div>
</body>
</html>
<script>
    $(document).ready(function () {
        $.ajax({
            url: '@Url.Action("GetTiposInconsistencias", "Rebajos")',
            method: 'GET',
            success: function (data) {
                console.log(data); // Verificar la respuesta en la consola
                var $comboBox = $('#comboBox3');
                $comboBox.empty();

                if (data && data.length > 0) {
                    $.each(data, function (index, tipo) {
                        $comboBox.append($('<option>', {
                            value: tipo.idTipoInconsistencia, // Asegúrate que los nombres de las propiedades coincidan
                            text: tipo.descripcion
                        }));
                    });
                } else {
                    $comboBox.append($('<option>', {
                        value: '',
                        text: 'No hay tipos de inconsistencia disponibles'
                    }));
                }
            },
            error: function () {
                $('#comboBox3').append($('<option>', {
                    value: '',
                    text: 'Error cargando los tipos de inconsistencia'
                }));
            }
        });
    });

    $(document).ready(function () {
        $.ajax({
            url: '@Url.Action("GetTiposRebajos", "SolicitudeRebajo")',
            method: 'GET',
            success: function (data) {
                var $comboBox = $('#comboBox4');
                $comboBox.empty();

                if (data && data.length > 0) {
                    $.each(data, function (index, tipo) {
                        $comboBox.append($('<option>', {
                            value: tipo.idTipoRebajo,
                            text: tipo.descripcion
                        }));
                    });
                } else {
                    $comboBox.append($('<option>', {
                        value: '',
                        text: 'No hay tipos disponibles'
                    }));
                }
            },
            error: function () {
                $('#comboBox3').append($('<option>', {
                    value: '',
                    text: 'Error'
                }));
            }
        });
    });
</script>